#!/bin/bash

#PBS -P xu32
#PBS -q normal

#PBS -l walltime=24:00:00
#PBS -l storage=scratch/xu32

#PBS -l mem=100gb
#PBS -l ncpus=16
#PBS -l wd

#PBS -M g.pierobon@unsw.edu.au
#PBS -m e 
#PBS -N output

module purge

export PYTHONPATH=/home/561/gp5547/gadget4-tools:$PYTHONPATH
source /home/561/gp5547/python_env/bin/activate
export OMP_NUM_THREADS=16

mkdir -p aout
mkdir -p aout/plots aout/delta aout/spectrum aout/profile aout/void  # ADD HERE 

FILE="ic1v_early/snap_003"   # For single file
DIR="ic1v_early"             # For single dir
NFILES=7

OPT=4                        # 0 = plot, 1 = spectrum, 2 = delta dump, 3 = VSF, 4 = void fraction, 5 = profile

MAP="pride"                  # Map type, only if OPT=0. Maps from cmasher are accepted 
VT=6                         # Snapshot to check for voids, only for OPT=3
THR=0.7                      # Void threshold for smoothing, only for OPT=3,4
DFI=6                        # Density profile snap number
NH=16                         # Number of halos to profile

# Single file
#python3 analyse_single.py $FILE $OPT $MAP $VT $THR

# Single dir first N files 
#python3 analyse_full.py $DIR $NFILES $OPT $MAP $VT $THR

# General
python3 analyse_full.py ic1v_late_v2 $NFILES $OPT $MAP 6 0.7 $DFI $NH   
python3 analyse_full.py ic1v_late_v2 $NFILES $OPT $MAP 6 0.65 $DFI $NH   
python3 analyse_full.py ic1v_late_v2 $NFILES $OPT $MAP 6 0.6 $DFI $NH   
python3 analyse_full.py ic1v_late_v2 $NFILES $OPT $MAP 6 0.55 $DFI $NH   
python3 analyse_full.py ic1v_late_v2 $NFILES $OPT $MAP 6 0.5 $DFI $NH   

python3 analyse_full.py ic1_late $NFILES $OPT $MAP 6 0.7 $DFI $NH   
python3 analyse_full.py ic1_late $NFILES $OPT $MAP 6 0.65 $DFI $NH   
python3 analyse_full.py ic1_late $NFILES $OPT $MAP 6 0.6 $DFI $NH   
python3 analyse_full.py ic1_late $NFILES $OPT $MAP 6 0.55 $DFI $NH   
python3 analyse_full.py ic1_late $NFILES $OPT $MAP 6 0.5 $DFI $NH   

